import Head from 'next/head'
import React from 'react'
import Header from './Header'

export default function Layout({children}) {
  return (
    <div>
      <Head>
        <title>Best Udemy Courses</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@200;400;500;700&display=swap" rel="stylesheet"/>
      </Head>
      <header className='fixed w-full top-0 z-40'>
        <Header/>
      </header>
      <main className='container mx-auto my-5 mt-28'>
        {children}
      </main>
    </div>
  )
}
